---

clusters:

- name: "{{TWEED_CLUSTER}}"
  region: ams2
  type: 512mb
  nodes: 1

services:

- name: redis
  image: "tutum.co/{{USER}}/redis"
  build: lib/redis
  containers: 1

- name: tweets
  image: "tutum.co/{{USER}}/tweets"
  build: lib/tweets
  containers: 1
  env:
    TWEED_TWITTER_CONSUMER_KEY: "{{TWEED_TWITTER_CONSUMER_KEY}}"
    TWEED_TWITTER_CONSUMER_SECRET: "{{TWEED_TWITTER_CONSUMER_SECRET}}"
    TWEED_TWITTER_ACCESS_TOKEN: "{{TWEED_TWITTER_ACCESS_TOKEN}}"
    TWEED_TWITTER_ACCESS_TOKEN_SECRET: "{{TWEED_TWITTER_ACCESS_TOKEN_SECRET}}"
  require:
    - redis

- name: feeds
  image: "tutum.co/{{USER}}/feeds"
  build: lib/feeds
  containers: 1
  require:
    - redis

- name: web
  image: "tutum.co/{{USER}}/web"
  build: lib/web
  containers: 1
  ports:
    - inner_port: 80
      outer_port: 80
      port_name: http
      protocol: tcp
      published: true
  env:
    NODE_ENV: production
    MINIFY: 1
    PORT: 80
  require:
    - redis
